sudo: required
language: go

go:
  - 1.12.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker build . -t sinoreps/cmppproxy:latest

after_success:
  - if [ ! -s "$TRAVIS_TAG" ] ; then
      docker tag sinoreps/cmppproxy:latest sinoreps/cmppproxy:$TRAVIS_TAG;
      echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
      docker push sinoreps/cmppproxy:$TRAVIS_TAG;

      docker tag sinoreps/cmppproxy:latest quay.io/sinoreps/cmppproxy:$TRAVIS_TAG;
      echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
      docker push quay.io/sinoreps/cmppproxy:$TRAVIS_TAG;
    fi